language: node_js

node_js:
  - 10.16.2

before_script:
  - rm package-lock.json
  - npm install

script:
- npm ci
- npm test
- npm pack

after_script:
- docker login -u cakhanif -p $docker_password
- docker build -t cakhanif/mail-mgmt-app:v1 .
- docker tag cakhanif/mail-mgmt-app:v1 cakhanif/mail-mgmt-app:latest
- docker push cakhanif/mail-mgmt-app:v1 cakhanif/mail-mgmt-app:latest

after_success:
# Submit coverage report to https://codecov.io
- bash <(curl -s https://codecov.io/bash)

# Monitor only these branches
branches:
  except:
    - null

# You can delete the cache using travis-ci web interface
cache:
  directories:
  - $HOME/node_modules